columns:
  - id
  - Gender
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Vehicle_Age
  - Vehicle_Damage
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage

numerical_columns:
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

target_column: Response

drop_columns:
  - id
